name: kelvinli
favicon: null
layout_spectrum: 0.10587
typography_spectrum: 0.9513893551193178
title: "Kelvin's Grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.9468032391741872
  saturation: 0.9919538414105773
  rhythmicContrast: 0.4585574804805219
purpose: []
