name: kelvinli
favicon: null
layout_spectrum: 0.10587
typography_spectrum: 0.24359
title: "Kelvin's Grid"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d9d9d9'
    - '#bababa'
    - '#e8e8e8'
    - '#c5c5c5'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
